In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
!pip install seaborn



In [4]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
 arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
arr2=np.array([[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [7]:
arr3=np.array([[1,2,3,4],[2,3,4,5]])
print(arr3)
arr3.shape

[[1 2 3 4]
 [2 3 4 5]]


(2, 4)

In [8]:
x=np.arange(0,10,2).reshape(5,1)
print(x)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [9]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
a=np.array([[1,2,3],[3,2,1]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)

[[1 2 3]
 [3 2 1]]
(2, 3)
2
6
int64
8


In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.linspace(0,3,100)

array([0.        , 0.03030303, 0.06060606, 0.09090909, 0.12121212,
       0.15151515, 0.18181818, 0.21212121, 0.24242424, 0.27272727,
       0.3030303 , 0.33333333, 0.36363636, 0.39393939, 0.42424242,
       0.45454545, 0.48484848, 0.51515152, 0.54545455, 0.57575758,
       0.60606061, 0.63636364, 0.66666667, 0.6969697 , 0.72727273,
       0.75757576, 0.78787879, 0.81818182, 0.84848485, 0.87878788,
       0.90909091, 0.93939394, 0.96969697, 1.        , 1.03030303,
       1.06060606, 1.09090909, 1.12121212, 1.15151515, 1.18181818,
       1.21212121, 1.24242424, 1.27272727, 1.3030303 , 1.33333333,
       1.36363636, 1.39393939, 1.42424242, 1.45454545, 1.48484848,
       1.51515152, 1.54545455, 1.57575758, 1.60606061, 1.63636364,
       1.66666667, 1.6969697 , 1.72727273, 1.75757576, 1.78787879,
       1.81818182, 1.84848485, 1.87878788, 1.90909091, 1.93939394,
       1.96969697, 2.        , 2.03030303, 2.06060606, 2.09090909,
       2.12121212, 2.15151515, 2.18181818, 2.21212121, 2.24242

In [16]:

del arr1

In [17]:
del arr2

In [18]:
arr1=np.array([1,2,-3,4,5])
arr2=np.array([5,4,3,2,1]) 
print("The additition of array:-",arr2+arr1)
print("The additition of array:-",arr2-arr1)
print("The additition of array:-",arr2*arr1)
print("The additition of array:-",arr2/arr1)


The additition of array:- [6 6 0 6 6]
The additition of array:- [ 4  2  6 -2 -4]
The additition of array:- [ 5  8 -9  8  5]
The additition of array:- [ 5.   2.  -1.   0.5  0.2]


In [19]:
print(np.sqrt(arr2))
print(np.absolute(arr1))

[2.23606798 2.         1.73205081 1.41421356 1.        ]
[1 2 3 4 5]


In [20]:
print(np.exp(arr1))
print(np.cos(arr1))

[2.71828183e+00 7.38905610e+00 4.97870684e-02 5.45981500e+01
 1.48413159e+02]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [21]:
arr=np.array([[1,2,3,4],[0,9,8,7],[6,5,4,3]])
print(arr)

[[1 2 3 4]
 [0 9 8 7]
 [6 5 4 3]]


In [22]:
print(arr[:2,1:3])

[[2 3]
 [9 8]]


In [23]:
print(arr[0][3])

4


In [24]:
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  0   9   8   7]
 [  6   5   4   3]]


In [25]:
np.mean(arr)

np.float64(12.583333333333334)

In [26]:
arr[0:,0:]=100
print(arr)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [27]:
np.mean(arr)

np.float64(100.0)

In [28]:
data=np.array([1,2,3,4,5])
x=np.mean(data)
print("The mean is :",np.mean(data))
y=np.std(data)
print("The standard devation is :",np.std(data))
#normalize the data
normalize_data=(data-x)/y
print(f"The normalize data is :{normalize_data}")

The mean is : 3.0
The standard devation is : 1.4142135623730951
The normalize data is :[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [29]:
new_data=np.array([1,2,3,4,5,6,7,8,9])
x=np.mean(new_data)
y=np.median(new_data)
z=np.std(new_data)
v=np.var(new_data)
print(f"The mean is :{x}")
print(f"The median is :{y}")
print(f"The standard_deviation is :{z}")
print(f"The varienv is :{v}")

The mean is :5.0
The median is :5.0
The standard_deviation is :2.581988897471611
The varienv is :6.666666666666667


In [30]:
new_data[~((new_data>4) & (new_data<9))]

array([1, 2, 3, 4, 9])

hii



In [31]:
new_data[~ (new_data>4)]

array([1, 2, 3, 4])

In [32]:
import pandas as pd

In [33]:
import pandas as pd
x=pd.Series((1,2,3,4,5,6))
print("the first pandas series:",x)
print(type(x))

the first pandas series: 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>


In [34]:
data=pd.Series({'a':1,'b':2,'c':3})
y={'a':1,'b':2,'c':3}
print(type(y))
print(data)

<class 'dict'>
a    1
b    2
c    3
dtype: int64


In [35]:
data=[10,20,30,40]
index=("1","2","3","4")
print(pd.Series(data,index))

1    10
2    20
3    30
4    40
dtype: int64


In [36]:
data=[{'Name':"Ayush","Age":24,"Place":"IIT MADRAS"},
         {'Name':"Deepa","Age":23,"Place":"IIT GUWAHATI"},
        {'Name':"Shivam","Age":26,"Place":"IIT roorkee"},
        {'Name':"Saurabh","Age":25,"Place":"IIT Ropar"}]
pd.DataFrame(data)

Name  Age         Place
0    Ayush   24    IIT MADRAS
1    Deepa   23  IIT GUWAHATI
2   Shivam   26   IIT roorkee
3  Saurabh   25     IIT Ropar

In [37]:
df=pd.read_csv('example.csv')
df.head(10)
#print(df)

name  age
0  Krish   32

In [38]:
df.tail()

name  age
0  Krish   32

In [39]:
df

name  age
0  Krish   32

In [40]:
df['Date']

KeyError: 'Date'

In [ ]:
df.loc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [ ]:
df.iloc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [ ]:
df

Transaction ID        Date Product Category  \
0             10001  2024-01-01      Electronics   
1             10002  2024-01-02  Home Appliances   
2             10003  2024-01-03         Clothing   
3             10004  2024-01-04            Books   
4             10005  2024-01-05  Beauty Products   
..              ...         ...              ...   
235           10236  2024-08-23  Home Appliances   
236           10237  2024-08-24         Clothing   
237           10238  2024-08-25            Books   
238           10239  2024-08-26  Beauty Products   
239           10240  2024-08-27           Sports   

                                        Product Name  Units Sold  Unit Price  \
0                                      iPhone 14 Pro           2      999.99   
1                                   Dyson V11 Vacuum           1      499.99   
2                                   Levi's 501 Jeans           3       69.99   
3                                  The Da Vinci Code           4       15.99   
4                            Neutrogena Skincare Set           1       89.99   
..                                               ...         ...         ...   
235  Nespresso Vertuo Next Coffee and Espresso Maker           1      159.99   
236                        Nike Air Force 1 Sneakers           3       90.00   
237           The Handmaid's Tale by Margaret Atwood           3       10.99   
238             Sunday Riley Luna Sleeping Night Oil           1       55.00   
239                       Yeti Rambler 20 oz Tumbler           2       29.99   

     Total Revenue         Region Payment Method  
0          1999.98  North America    Credit Card  
1           499.99         Europe         PayPal  
2           209.97           Asia     Debit Card  
3            63.96  North America    Credit Card  
4            89.99         Europe         PayPal  
..             ...            ...            ...  
235         159.99         Europe         PayPal  
236         270.00           Asia     Debit Card  
237          32.97  North America    Credit Card  
238          55.00         Europe         PayPal  
239          59.98           Asia    Credit Card  

[240 rows x 9 columns]

In [ ]:
df.at[230,'Date']

'2024-08-18'

In [ ]:
df.iat[230,3]

'Adidas Originals Trefoil Hoodie'

In [ ]:
data=[{'Name':"Ayush","Age":24,"Place":"IIT MADRAS"},
         {'Name':"Deepa","Age":23,"Place":"IIT GUWAHATI"},
        {'Name':"Shivam","Age":26,"Place":"IIT roorkee"},
        {'Name':"Saurabh","Age":25,"Place":"IIT Ropar"}]
x=pd.DataFrame(data)
print(x)

      Name  Age         Place
0    Ayush   24    IIT MADRAS
1    Deepa   23  IIT GUWAHATI
2   Shivam   26   IIT roorkee
3  Saurabh   25     IIT Ropar


In [ ]:
x['CGPA']=[6.75,7.2,8.5,8.1]
print(x)

      Name  Age         Place  CGPA
0    Ayush   24    IIT MADRAS  6.75
1    Deepa   23  IIT GUWAHATI  7.20
2   Shivam   26   IIT roorkee  8.50
3  Saurabh   25     IIT Ropar  8.10


In [ ]:
dropped=x.drop('CGPA',axis=1)
print(dropped)

      Name  Age         Place
0    Ayush   24    IIT MADRAS
1    Deepa   23  IIT GUWAHATI
2   Shivam   26   IIT roorkee
3  Saurabh   25     IIT Ropar


In [ ]:
print(x)

      Name  Age         Place  CGPA
0    Ayush   24    IIT MADRAS  6.75
1    Deepa   23  IIT GUWAHATI  7.20
2   Shivam   26   IIT roorkee  8.50
3  Saurabh   25     IIT Ropar  8.10


In [ ]:
x['Age']=x['Age']+2
print(x)

      Name  Age         Place  CGPA
0    Ayush   26    IIT MADRAS  6.75
1    Deepa   25  IIT GUWAHATI  7.20
2   Shivam   28   IIT roorkee  8.50
3  Saurabh   27     IIT Ropar  8.10


In [ ]:
x.drop(0)

Name  Age         Place  CGPA
1    Deepa   25  IIT GUWAHATI   7.2
2   Shivam   28   IIT roorkee   8.5
3  Saurabh   27     IIT Ropar   8.1

In [ ]:
df=pd.read_csv("example.csv")
df.describe()

Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [ ]:
with open("data.csv",'w') as x:
    x.write("")

In [ ]:
import pandas as pd
df=pd.read_csv('data.csv')
df.head(5)
df.tail(5)
df.describe()
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [ ]:
df.isnull()

Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [ ]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
df.fillna(0)

Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df['Sales']=df['Sales'].fillna(df['Sales'].mean())
df.isnull().sum()


Date        0
Category    0
Value       3
Product     0
Sales       0
Region      0
dtype: int64

In [ ]:
df['Value']=df['Value'].fillna(df['Value'].mean())
df.isnull().sum()
df

KeyError: 'Value'

In [ ]:
import pandas as pd
df=pd.read_csv("example.csv")

df.describe()

Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [ ]:
df.head()

Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  
0           2      999.99        1999.98  North America    Credit Card  
1           1      499.99         499.99         Europe         PayPal  
2           3       69.99         209.97           Asia     Debit Card  
3           4       15.99          63.96  North America    Credit Card  
4           1       89.99          89.99         Europe         PayPal

In [ ]:
df=df.rename(columns={'Date':'Sales_Date'})
df.head()

Transaction ID  Sales_Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  
0           2      999.99        1999.98  North America    Credit Card  
1           1      499.99         499.99         Europe         PayPal  
2           3       69.99         209.97           Asia     Debit Card  
3           4       15.99          63.96  North America    Credit Card  
4           1       89.99          89.99         Europe         PayPal

In [ ]:
df.dtypes

Transaction ID        int64
Sales_Date           object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [ ]:
df['Unit_price_new']=df['Unit Price'].astype(int)
df.head()

Transaction ID  Sales_Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  \
0           2      999.99        1999.98  North America    Credit Card   
1           1      499.99         499.99         Europe         PayPal   
2           3       69.99         209.97           Asia     Debit Card   
3           4       15.99          63.96  North America    Credit Card   
4           1       89.99          89.99         Europe         PayPal   

   Unit_price_new  
0             999  
1             499  
2              69  
3              15  
4              89

In [ ]:
df['Total Revenue_new']=df['Total Revenue'].apply(lambda x:x*2)
df.head()

Transaction ID  Sales_Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  \
0           2      999.99        1999.98  North America    Credit Card   
1           1      499.99         499.99         Europe         PayPal   
2           3       69.99         209.97           Asia     Debit Card   
3           4       15.99          63.96  North America    Credit Card   
4           1       89.99          89.99         Europe         PayPal   

   Unit_price_new  Total Revenue_new  
0             999            3999.96  
1             499             999.98  
2              69             419.94  
3              15             127.92  
4              89             179.98

In [ ]:
x=df.groupby('Product Category')['Total Revenue'].mean()
print(x)

Product Category
Beauty Products     65.54750
Books               46.54825
Clothing           203.22325
Electronics        874.56025
Home Appliances    466.15400
Sports             358.16300
Name: Total Revenue, dtype: float64


In [ ]:
x=df.groupby(['Product Category','Region'])['Total Revenue'].sum()
print(x)

Product Category  Region       
Beauty Products   Europe            2621.90
Books             North America     1861.93
Clothing          Asia              8128.93
Electronics       North America    34982.41
Home Appliances   Europe           18646.16
Sports            Asia             14326.52
Name: Total Revenue, dtype: float64


In [ ]:
x=df.groupby(['Payment Method','Region'])['Total Revenue'].agg(('mean','sum','count'))
x

mean       sum  count
Payment Method Region                                   
Credit Card    Asia           358.16300  14326.52     40
               North America  460.55425  36844.34     80
Debit Card     Asia           203.22325   8128.93     40
PayPal         Europe         265.85075  21268.06     80

In [ ]:
df1=pd.DataFrame({'key':['A','B','C'], 'value1':[1,2,3]})
df1



key  value1
0   A       1
1   B       2
2   C       3

In [ ]:
df2=pd.DataFrame({'key':['D','A','C'], 'value2':[3,2,1]})
df2

key  value2
0   D       3
1   A       2
2   C       1

In [ ]:
#merging data frame on Key value
pd.merge(df1,df2,on='key',how='inner')

key  value1  value2
0   A       1       2
1   C       3       1

In [ ]:
pd.merge(df1,df2,on='key',how='outer')

key  value1  value2
0   A     1.0     2.0
1   B     2.0     NaN
2   C     3.0     1.0
3   D     NaN     3.0